GET http://localhost:3000/customer/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDNmNjY0MzFmODViNmFhM2VlZjgyOWYiLCJpYXQiOjE2ODE5ODAwMzMsImV4cCI6MTY4MjE1MjgzM30.fMMQ8TyRyjk-bAEya37LiWoU5nLDGqOnLpGYrJ6vpSg
###

POST  http://localhost:3000/customer/login
Content-Type: application/json

{
    "Email": "ThuongVU90@gmail.com",
"Password": "09778548"
}
